### ISSUE TITLE
[proposal] Support worker_processes_spare

### ISSUE THREAD

**Issue by kazeburo** [matsumotory/ngx_custom_worker_module#1]
worker_processes are useful, but sometimes we don't want all the cores to be used.
On a high-traffic server, when logrotate is used for log compression, gzip and worker processings overlap, causing a slowdown in response time.
We could avoid the slowdown in response time by setting worker_processes to a number slightly less than the number of CPU cores when building server.

But I want to achieve it only in the nginx configuration like bellow.

```
# the number of worker processes is __6__ if the number of cpu threads is 8.
worker_processes        auto;
worker_processes_spare 2;
```

Current my working branch is here.
https://github.com/matsumotory/ngx_custom_worker_module/compare/master...kazeburo:add-spare

**Comment by matsumotory** [comment]
@kazeburo Thank you for your proposal. I also think the feature is useful. Cloud you send me the PR via your working branch?

**Comment by matsumotory** [comment]
Supported via #2
